version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
        command: "/bin/bash"

    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install nodejs
      - run: sudo mv /usr/bin/nodejs /usr/bin/node
      - run : ./.circleci/install-maven
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies- # fallback if cache not found

      - run: clojure -A:test-jvm

      - run: clojure -A:shadow compile test

      - run: ./deploy.sh

#      - persist_to_workspace:
#          root: .
#          paths:
#            - target

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}