#!/usr/bin/env bash


cd `dirname $0`


mkdir target
cd target

wget http://apache.mediamirrors.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
tar xzvf apache-maven-3.6.3-bin.tar.gz

dir=$(pwd)

ln -s $dir/apache-maven-3.6.3/bin/mvn /usr/local/bin/mvn